### ISSUE TITLE
Choosing an affiliate at checkout with an active affiliate link

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-checkout-referrals#27] opened 2019-03-27 19:36 UTC
If you visit this link, you should _not_ be able to choose an affiliate at checkout, in this case when you register: http://s14890.p27.sites.pressdns.com/register/ref/3/. However, when you first visit this link, you're still able to choose a different affiliate: 

![slack-imgs](https://user-images.githubusercontent.com/4752949/55106601-af3d6700-50cf-11e9-95a5-77a088bdc8c7.gif)

Upon refresh your are _not_ able to. But, this should not be an option.

This came up on this ticket: https://secure.helpscout.net/conversation/805297520/103133?folderId=634609.  

This seems to be linked to https://github.com/AffiliateWP/affiliatewp-checkout-referrals/issues/21, which was fixed with PR https://github.com/AffiliateWP/affiliatewp-checkout-referrals/pull/22.

**Comment by michaelbeil** [comment] 2019-04-08 17:06
The [same customer](https://secure.helpscout.net/conversation/805297520/103133?folderId=634609) is getting in touch with us again about this issue.

**Comment by michaelbeil** [comment] 2019-05-31 09:48
The [customer](https://secure.helpscout.net/conversation/865910599/121802?folderId=634609) that made us aware of this issue, connected with us again to see if this issue will be fixed. I told him that we are aware of the [issue](https://github.com/AffiliateWP/affiliatewp-checkout-referrals/issues/27#issue-426147640), but I do not have an ETA on when it will be fixed. 

Is anyone else able to replicate this issue?

**Comment by DrewAPicture** [comment] 2019-05-31 10:47
@michaelbeil Can you have the customer reactivate AffiliateWP on their staging site so others can try to reproduce it?

**Comment by michaelbeil** [comment] 2019-05-31 12:31
Good idea. I just tried reactivating AffiliateWP on our testing site, but I am still able to replicate this when I visit http://s14890.p27.sites.pressdns.com/rcp/register/ref/3/: 
![image](https://user-images.githubusercontent.com/4752949/58705849-aeb39c00-83b0-11e9-949b-4c17a758b626.png)
However, I can ask the customer to do this as well.

**Comment by gspice** [comment] 2019-06-04 15:55
I reproduced this on his staging site, latest credentials are on this ticket:
https://secure.helpscout.net/conversation/865910599/121802?folderId=1170842

Also to note:
* Specific to the RCP integration
* The issue appears to happen only if pretty links are used, when using /?ref=x the CR dropdown list was not visible.

**Comment by nosegraze** [comment] 2019-12-19 12:57
PR: #34

Not sure if there's a specific reason for not wanting to use `get_fallback_affiliate_id()` but this fix works for me in RCP. Seems like the main issue is that simply checking the affiliate ID in `$_GET` will just never work with pretty permalinks. But `get_fallback_affiliate_id()` looks to have a fallback for very specifically checking that.

**Comment by DrewAPicture** [comment] 2019-12-19 16:24
Thanks for the consult and PR @nosegraze! 🙌

**Comment by DrewAPicture** [comment] 2019-12-19 16:28
Confirmed the fix and merged #34.

**Closed by DrewAPicture** 2019-12-19 16:28 UTC
Labels: integration-rcp, priority-medium, type-bug, workflow-has-hs-to-notify
