### ISSUE TITLE
Add a filter hook that grabs the choices in the dropdown and returns an alphabetized list

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-checkout-referrals#15] opened 2018-02-04 23:38 UTC
A request from a customer:

>a filter hook that grabs the array (or object) of the choices in the dropdown, puts them in order, and returns the alphabetized list

https://secure.helpscout.net/conversation/511995840/74759/?folderId=205529

**Comment by michaelbeil** [comment] 2018-03-17 22:29
Another request: https://secure.helpscout.net/conversation/543394430/78358?folderId=205524.

**Comment by gspice** [comment] 2018-08-20 16:25
Another request for this, he has a lot of affiliates:
https://secure.helpscout.net/conversation/644996530/88274?folderId=205524

**Comment by gspice** [comment] 2019-02-25 22:05
Another request, wants a sort order option:
https://secure.helpscout.net/conversation/787499730/101595?folderId=205524

>Please can this be changed or an option added so that the sorting is determined by the user's Last Name?

**Comment by gspice** [comment] 2019-10-02 20:03
Request to have the option to sort by name in a pre-sales HS ticket:
https://secure.helpscout.net/conversation/969541933/133100/

>Most important, if a list / select option is set, how are the names listed? Are they alphabetical according to last name? First name? Username? or are they listed according to the order they were entered into the system.I am using another system right now and they are only giving me an option to list according to the order they were entered. This does not work when you have several affiliates and someone has to search through a long list that seems to have no order since the names are all scrambled . Basically can these affiliates be listed alphabetically in some way?

**Comment by gspice** [comment] 2019-10-03 16:54
Another request for a code snippet or setting to sort the affiliate list alphabetically:
https://secure.helpscout.net/conversation/970699903/133269/

>Affiliate Referral Selection At Checkout
At checkout our customers can select which affiliate this sale belongs to. We want this to be required, but if they've purchased without using an affiliate we needed something for them to select. So I created an affiliate called "affiliate not listed" the problem is now that there have been affiliates generated after, this "affiliate not listed" is not at the top of the list anymore. Is there an easy bit of code that I could insert in to fix that? If we can have this list alphabetically that would be ideal.

**Comment by michaelbeil** [comment] 2019-11-18 15:56
I received a request to sort the affiliate list alphabetically:
>Client would like to see the list of affiliates in the dropdown select menu in alphabetical oder, and that makes sense to me as well. I have a child theme and can edit php, can you help me make that happen?

**Comment by gspice** [comment] 2020-02-06 20:35
Another request to be able to sort the list:
https://secure.helpscout.net/conversation/1076046881/144831?folderId=205524


>Affiliates shown in random order - need to alphabetize
Hi, currently affiliates are being shown in a random order. To make this easy for customer to select affiliates, it would be REALLY nice for the dropdown to sort by alphabetical order - either by first or last name. Can you please fix this or send me a code snippet that I can use to fix this?You can see https://bibleinstories.com/checkout/ to see what I mean.

**Comment by michaelbeil** [comment] 2020-05-20 11:43
Another [customer](https://secure.helpscout.net/conversation/1169925827/154715/) wants to sort the list alphabetically:
>Right now it is sorting with the newest affiliate at the top of the list. It should be alphabetically so that as the list grows, people can easily find who they are looking for.

**Comment by DrewAPicture** [comment] 2020-06-25 22:58
Note: The suggestion is to simply alphabetize list of affiliates (currently ordered by affiliate ID), and then separately supply a filter on the results, should a customer enjoy the seemingly random we're currently displaying.

**Comment by gspice** [comment] 2021-01-05 20:09
Another request to be able to sort the list of affiliates in alpha order:
https://secure.helpscout.net/conversation/1386422675/174258/

>Hi I was wondering if this drop down list can be alphabetical.
Wanted to see if coding could make this add on drop down list alphabetically or in some sort of order. Right now it seems it may be random or in the order that it is added to the site

**Comment by DrewAPicture** [comment] 2021-01-06 15:03
@amdrew What say you? Shall we alphabetize the list?

**Comment by tjackson1317** [comment] 2021-01-07 02:23
Two additional requests for this:

https://secure.helpscout.net/conversation/1368145435/173042/
https://secure.helpscout.net/conversation/1388816323/174475/

**Comment by amdrew** [comment] 2021-01-07 02:51
@DrewAPicture Yeah let's do it.

Since we're introducing a new option for ordering, I'd still prefer if we kept the current sort order (Affiliate ID) as the default, and added the new alphabetical sort order as something customers needed to select. This would provide the least amount of disruption (it's possible we could get some support tickets on why it has suddenly changed) for the 900+ active installs, and also satisfy those who are requesting it.

**Comment by dbeja** [comment] 2021-01-07 16:33
@amdrew and @DrewAPicture Should this be a toggle option on the cart when the user needs to select the affiliate or a general setting on Affiliate Settings?

Also, what if we also replace the dropdown with a select2 input with ajax and search filter as we have on Product Rates Add-on?

**Comment by amdrew** [comment] 2021-01-07 21:00
@dbeja A settings option within the admin current settings for Checkout Referrals. If you haven't seen these already (because they are hard to find) they're on the "Integrations" tab of AffiliateWP.

<img width="725" alt="Screen Shot 2021-01-08 at 9 56 58 AM" src="https://user-images.githubusercontent.com/52581/103943958-dc211800-5197-11eb-9fd0-5ed4c45b83c3.png">

> Also, what if we also replace the dropdown with a select2 input with ajax and search filter as we have on Product Rates Add-on?

That's something we'd absolutely like to do to make it easier for customers to find affiliates. We'll handle that at some point in: https://github.com/AffiliateWP/affiliatewp-checkout-referrals/issues/3

**Comment by dbeja** [comment] 2021-01-08 17:00
@amdrew PR created here: #42

**Comment by tjackson1317** [comment] 2021-04-09 15:25
> Checkout Referrals addon, Affiliate order update in the list
> I'm using AffiliateWP and Checkout Referrals to show list of Affiliates on the checkout page, and this works very good. I'm just wondering is it possible to change order of Affiliates in this list? And if so, how to change it? Default order is order by adding Affiliate (by date).

https://secure.helpscout.net/conversation/1479045429/182114?folderId=205529

**Comment by DrewAPicture** [comment] 2021-04-09 18:10
Merged #42 against `release/1.0.9`

**Closed by DrewAPicture** 2021-04-09 18:10 UTC
Labels: type-improvement, workflow-has-hs-to-notify
